baseURL = "https://ruskicoder.github.io/fcj-skyline2-proposal/"
relativeURLs = true
canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# Enable automatic last modified date tracking
enableGitInfo = true

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod", "date"]

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = "InsightHR - HR Automation Platform Proposal"
  author = "FCJ SkyLine2 Team"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "InsightHR - HR Automation Platform"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "InsightHR - Nền tảng Tự động hóa Nhân sự"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20
